services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  db:
    image: postgres:16
    container_name: laravel_postgres_db
    environment:
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_pass
      POSTGRES_DB: laravel_db
    ports:
      - "5434:5432"  # port local différent pour éviter conflit avec ton PostgreSQL host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel_user -d laravel_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: laravel_pgadmin_web
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5052:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - mynetwork

volumes:
  postgres_data:
  pgadmin_data:

networks:
  mynetwork:
    driver: bridge
