<?php

namespace App\Providers;

// use Illuminate\Support\Facades\Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Carbon\Carbon;
use Laravel\Passport\Passport;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The model to policy mappings for the application.
     *
     * @var array<class-string, class-string>
     */
    protected $policies = [
        //
    ];

    /**
     * Register any authentication / authorization services.
     */
    public function boot(): void
    {
        // Configure Passport token lifetimes and keys (if Passport is installed)
        if (class_exists(Passport::class)) {
            // Enable the password grant (Passport >=12 disables it by default).
            // See vendor/laravel/passport/UPGRADE.md — call enablePasswordGrant()
            Passport::enablePasswordGrant();
                Passport::tokensExpireIn(now()->addDays(1));
            // Refresh tokens: 30 days
            Passport::refreshTokensExpireIn(Carbon::now()->addDays(30));
                Passport::personalAccessTokensExpireIn(now()->addMonths(6));
            // Use RSA keys generated by `php artisan passport:install` (Passport default uses RS256)
            // No further changes required here for RS256.
        }
    }
}
